name: UltimateAuraPro
version: 1.0
author: dandrew7
main: me.dandrew.ultimateaurapro.UltimateAuraProPlugin
api-version: 1.13
softdepend: [Citizens]

commands:
  aura:
      usage: /<command>
      description: cool auras